### ISSUE TITLE
Bug: Runtime error when pressing delete button

### ISSUE THREAD

**Issue by CaseyJohnson-RS** [Racoon11/OurProject#2]
1.Description of error
The application crashes when you click the "Delete" button

2. Initial conditions
Just launch the application

3. Expected result
Nothing happens

4. Result made
The app crashes

![image](https://github.com/Racoon11/OurProject/assets/66686838/72f7da49-0010-494a-bfec-46ae6c01482b)
![image](https://github.com/Racoon11/OurProject/assets/66686838/b964d759-d93c-4139-9d92-7895404354eb)

**Comment by CaseyJohnson-RS** [comment]
Shame on u

**Comment by Racoon11** [comment]
Issue is resolved in commit 2f244ea45b3c3e22f3bf5de718b0c12ddb6aefd2
